# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 726b19d860cdf2dcf152a4f821a0bcd12a17eb7295d98581b8e456df68b3ae072546035bcfc53a856235516453fb1697da40eddc1391c2a8681bc39a7ab99b30

test:
  secret_key_base: 310bb0c44b1b714f1eaa690cf3466837a12f8bbe727300034aefa0f75af362a37022f07d361780c68c1a7b7e062a7cbabe4648945cad5fae06c93bd3226b91bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: askjdhaskjdhasjdhasjdkjashdjsajdhakjsdjsahkjdsakhdjashdsajkdhsakjdhaskjdhsajkhdjksahdkjashdkjashdkjsaoieruoweur94238509485weklrhjsfhkjdshfkjdskfhdskjdfs
